name: just test actions
on:
  push:
  schedule:
    - cron: "* */10 * * *"

jobs:
  ts1:
    runs-on: ubuntu-latest
    steps:
      - name: checkout loacal repo
        uses: actions/checkout@v2
      - name: first
        run: |
          my_num=4
          echo ${my_num}
      - name: second
        if: ${{steps.first.outputs.num > 3}}
        run: |
          echo "okkkkk"
        
