name: just test actions
on:
  push:

jobs:
  ts1:
    runs-on: ubuntu-latest
    steps:

      - name: download artifact
        uses: actions/download-artifact@v2
        with:
          name: number
      - name: read artifact
        run: |
          content=$(cat ts.txt)
          echo file-content
          echo $content