name: just test actions
on:
  push:

jobs:
  ts1:
    runs-on: ubuntu-latest
    steps:
      - name: checkout loacal repo
        uses: actions/checkout@v2
      - name: generate txt
        run: |
          cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
          data=$(date +"%Y%m%d.%H%M%S")
          echo $data > a.txt
      - name: commit
        uses: elstudio/actions-js-build/commit@v4
        with:
          commitMessage: auto commit