name: just test actions
on:
  push:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  ts1:
    runs-on: ubuntu-latest
    steps:
      - name: checkout loacal repo
        uses: actions/checkout@v2
      - name: first
        id: first
        run: |
          my_num=2
          echo "::set-output name=num::${my_num}"
      - name: second
        if: ${{steps.first.outputs.num > 1}}
        run: |
          echo "okkkkk"
        