name: just test actions
on:
  push:

jobs:
  ts1:
    runs-on: ubuntu-latest
    steps:

      - name: generate txt
        run: |
          cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
          echo $(date +"%Y%m%d.%H%M%S") > a.txt
      - name: commit
        usese: elstudio/actions-js-build/commit@v4
        with:
          commitMessage: auto commit